const events = [ 
  { Day: 'Sunday',
    Time: '5:00',
    'Event Name': 'The Return of Jedi Outcast',
    'Staff Name': 'Pasquale and Gabe T',
    Color: '5B7286' },
  { Day: '',
    Time: '5:15',
    'Event Name': 'Geoguesser',
    'Staff Name': 'Lise and Zach T',
    Color: '' },
  { Day: '',
    Time: '5:15',
    'Event Name': 'Jackbox',
    'Staff Name': 'Michael ',
    Color: '' },
  { Day: '',
    Time: '6:30',
    'Event Name': 'Smash Bros',
    'Staff Name': 'Matt R',
    Color: '' },
  { Day: '',
    Time: '6:30',
    'Event Name': 'Roblox Arsenal',
    'Staff Name': 'Pierce and Connor',
    Color: '' },
  { Day: '',
    Time: '7:00',
    'Event Name': 'Codenames',
    'Staff Name': 'Zach S, Zermina, Natalia, and Elliot',
    Color: '' },
  { Day: '',
    Time: '7:00',
    'Event Name': 'Creating An Army of Moths - Sky, Children of Light',
    'Staff Name': 'Cath ',
    Color: '' },
  { Day: '',
    Time: '7:30',
    'Event Name': 'Tripping Gentlemen and Stumbling Fellows',
    'Staff Name': 'Ben D',
    Color: '' },
  { Day: '',
    Time: '7:30',
    'Event Name': 'Gartic Phone',
    'Staff Name': 'Zach T',
    Color: '' },
  { Day: '',
    Time: '8:00',
    'Event Name': 'Shell Shockers',
    'Staff Name': 'Ben F',
    Color: '' },
  { Day: '',
    Time: '8:00',
    'Event Name':
     'Fighting Radiant Oblobbles but Every Time we Die we do 5 Push-Ups',
    'Staff Name': 'Andrew, Matt S, and Aaron',
    Color: '' },
  { Day: '',
    Time: '',
    'Event Name': '',
    'Staff Name': '',
    Color: '' },
  { Day: 'Monday',
    Time: '6:30',
    'Event Name': 'Two Rooms and a Boom',
    'Staff Name': 'Geoffery ',
    Color: '' },
  { Day: '',
    Time: '6:30',
    'Event Name': 'Intro to pokemon shodown',
    'Staff Name': 'Matt R',
    Color: '' },
  { Day: '',
    Time: '6:30',
    'Event Name': 'Gartic Phone',
    'Staff Name': 'Zach T',
    Color: '' },
  { Day: '',
    Time: '7:00',
    'Event Name': 'Old Man Tails',
    'Staff Name': 'Aaron',
    Color: '' },
  { Day: '',
    Time: '7:00',
    'Event Name': 'Minecraft Scavenger Hunt',
    'Staff Name': 'Mac',
    Color: '' },
  { Day: '',
    Time: '7:30',
    'Event Name': 'Cath Explains her Old Art',
    'Staff Name': 'Cath',
    Color: '' },
  { Day: '',
    Time: '8:00',
    'Event Name': 'Minecraft Hypixel Party Games',
    'Staff Name': 'Zach T',
    Color: '' },
  { Day: '',
    Time: '8:00',
    'Event Name': 'Home Run Derby Watch Party',
    'Staff Name': 'John',
    Color: '' },
  { Day: '',
    Time: '',
    'Event Name': '',
    'Staff Name': '',
    Color: '' },
  { Day: 'Tuesday',
    Time: '6:30',
    'Event Name':
     'Basketball at 6:30 While it\'s still Light Out 2  RE-EVOLVED',
    'Staff Name': 'Keven',
    Color: '' },
  { Day: '',
    Time: '6:30',
    'Event Name': 'Speedrunning Freddi Fish 2',
    'Staff Name': 'Ben D',
    Color: '' },
  { Day: '',
    Time: '7:00',
    'Event Name': 'Trivia Night',
    'Staff Name': 'Gabe E',
    Color: '' },
  { Day: '',
    Time: '7:00',
    'Event Name': 'Destiny\'s Chill Hour',
    'Staff Name': 'Destiny',
    Color: '' },
  { Day: '',
    Time: '7:30',
    'Event Name': 'Great Big Bus Adventure',
    'Staff Name': 'Cath',
    Color: '' },
  { Day: '',
    Time: '7:30',
    'Event Name': 'America\'s All Star Pastime ',
    'Staff Name': 'John Muscle',
    Color: '' },
  { Day: '',
    Time: '8:00',
    'Event Name': 'TF Tuesday ',
    'Staff Name': 'Timo and Julian',
    Color: '' },
  { Day: '',
    Time: '8:00',
    'Event Name':
     'Zach Destroys Amazon Customer Service with Kindess and Reason',
    'Staff Name': 'Zach T',
    Color: '' },
  { Day: '',
    Time: '',
    'Event Name': '',
    'Staff Name': '',
    Color: '' },
  { Day: 'Wednesday',
    Time: '6:30',
    'Event Name': 'Reading the INTERCAL Manual',
    'Staff Name': 'Ben F and Ryan S',
    Color: '' },
  { Day: '',
    Time: '6:30',
    'Event Name': 'RETURN OF THE RETURN OF JEDI OUTCAST',
    'Staff Name': 'Gabe T',
    Color: '' },
  { Day: '',
    Time: '7:00',
    'Event Name': 'Let\'s be Cringe',
    'Staff Name': 'Samantha and Siobhan',
    Color: '' },
  { Day: '',
    Time: '7:00',
    'Event Name': '"Beautiful Bugs: Debugging Art and the Art of Debugging."',
    'Staff Name': 'Guest Speaker Rachel Ehrlich',
    Color: '' },
  { Day: '',
    Time: '7:30',
    'Event Name': 'The hunt for the lost Gnomes',
    'Staff Name': 'Gabe T',
    Color: '' },
  { Day: '',
    Time: '7:30',
    'Event Name': 'Dispelling the Anti-Weezer Sentiment',
    'Staff Name': 'Pasquale',
    Color: '' },
  { Day: '',
    Time: '8:00',
    'Event Name': 'Rythm Games',
    'Staff Name': 'Christian',
    Color: '' },
  { Day: '',
    Time: '8:00',
    'Event Name': 'Jackbox (or whatever)',
    'Staff Name': 'Michael',
    Color: '' },
  { Day: '',
    Time: '',
    'Event Name': '',
    'Staff Name': '',
    Color: '' },
  { Day: 'Thursday',
    Time: '6:30',
    'Event Name': 'Smash Tournament',
    'Staff Name': 'Pierce B',
    Color: '' },
  { Day: '',
    Time: '6:30',
    'Event Name': 'Spectacualr Spiderman Watch Party',
    'Staff Name': 'Gabe S',
    Color: '' },
  { Day: '',
    Time: '7:00',
    'Event Name': 'Discussing the ABA NBA Merger',
    'Staff Name': 'Keven',
    Color: '' },
  { Day: '',
    Time: '7:00',
    'Event Name': 'Team Fight Thursday',
    'Staff Name': 'Zach S and Elliot',
    Color: '' },
  { Day: '',
    Time: '7:30',
    'Event Name': 'TNS',
    'Staff Name': '',
    Color: '' },
  { Day: '',
    Time: '',
    'Event Name': '',
    'Staff Name': '',
    Color: '' },
  { Day: 'Friday',
    Time: '12:30',
    'Event Name': 'Gartic Phone',
    'Staff Name': 'Michael and Gabe T',
    Color: '' },
  { Day: '',
    Time: '12:30',
    'Event Name': 'Shell Shockers-ed',
    'Staff Name': 'Ben F',
    Color: '' },
  { Day: '',
    Time: '1:00',
    'Event Name': 'Connect Four Square',
    'Staff Name': 'Aaron and Matt S',
    Color: '' },
  { Day: '',
    Time: '1:00',
    'Event Name': 'Saying Farewell to Connor Karr',
    'Staff Name': 'Joey',
    Color: '' },
 ];
const test_events = [
	{ Day: 'Sunday',
    Time: '5:00',
    'Event Name': 'The Return of Jedi Outcast',
    'Staff Name': 'Pasquale and Gabe T',
    Color: '5B7286' },
  { Day: '',
    Time: '5:15',
    'Event Name': 'Geoguesser',
    'Staff Name': 'Lise and Zach T',
    Color: '' },
  { Day: '',
    Time: '5:15',
    'Event Name': 'Jackbox',
    'Staff Name': 'Michael ',
    Color: '' },
  { Day: '',
    Time: '6:30',
    'Event Name': 'Smash Bros',
    'Staff Name': 'Matt R',
    Color: '' },
  { Day: '',
    Time: '6:30',
    'Event Name': 'Roblox Arsenal',
    'Staff Name': 'Pierce and Connor',
    Color: '' },
  { Day: '',
    Time: '7:00',
    'Event Name': 'Codenames',
    'Staff Name': 'Zach S, Zermina, Natalia, and Elliot',
    Color: '' },
  { Day: '',
    Time: '7:00',
    'Event Name': 'Creating An Army of Moths - Sky, Children of Light',
    'Staff Name': 'Cath ',
    Color: '' },
  { Day: '',
    Time: '7:30',
    'Event Name': 'Tripping Gentlemen and Stumbling Fellows',
    'Staff Name': 'Ben D',
    Color: '' },
  { Day: '',
    Time: '7:30',
    'Event Name': 'Gartic Phone',
    'Staff Name': 'Zach T',
    Color: '' },
  { Day: '',
    Time: '8:00',
    'Event Name': 'Shell Shockers',
    'Staff Name': 'Ben F',
    Color: '' },
  { Day: '',
    Time: '8:00',
    'Event Name':
     'Fighting Radiant Oblobbles but Every Time we Die we do 5 Push-Ups',
    'Staff Name': 'Andrew, Matt S, and Aaron',
    Color: '' },
  { Day: '',
    Time: '',
    'Event Name': '',
    'Staff Name': '',
    Color: '' },
  { Day: 'Monday',
    Time: '6:30',
    'Event Name': 'Two Rooms and a Boom',
    'Staff Name': 'Geoffery ',
    Color: '' },
 ];
//let temp = document.querySelector(".container").getChildren();
let tableRow_template = document.querySelector(".template_row").childNodes[1];
let holder;



let currentDay = 'Sunday';
let currentTable;
 for(let event of events){
 	//Check or update the current Table
 	if(  event.Day !== currentDay && event.Day !== '' )
 		currentDay = event.Day;

 	console.log("Current Day: " + currentDay);

 	//go to the correct table(Sunday-Friday row)
 	currentTable = document.querySelector( "." + currentDay + "-table") ;


 	holder = tableRow_template.cloneNode(true); //Create a new empty row(not yet added)
 	console.log()
 	//Set the correct tvalues of that row
 	holder.querySelector(".event-time").innerText = event.Time;
 	holder.querySelector(".event-title").innerText = event['Event Name'];
 	holder.querySelector(".event-staff").innerText = event['Staff Name']; 

 	//Append the row the current table
 	currentTable.appendChild(holder); 


 

 }
 // document.querySelector(".container").appendChild(clonedRow);