
const test_events = [
	{ Day: 'Sunday',
    Time: '5:00',
    'Event Name': 'The Return of Jedi Outcast',
    'Staff Name': 'Pasquale and Gabe T',
    Color: '5B7286' },
  { Day: '',
    Time: '5:15',
    'Event Name': 'Geoguesser',
    'Staff Name': 'Lise and Zach T',
    Color: '' },
  { Day: '',
    Time: '5:15',
    'Event Name': 'Jackbox',
    'Staff Name': 'Michael ',
    Color: '' },
  { Day: '',
    Time: '6:30',
    'Event Name': 'Smash Bros',
    'Staff Name': 'Matt R',
    Color: '' },
  { Day: '',
    Time: '6:30',
    'Event Name': 'Roblox Arsenal',
    'Staff Name': 'Pierce and Connor',
    Color: '' },
  { Day: '',
    Time: '7:00',
    'Event Name': 'Codenames',
    'Staff Name': 'Zach S, Zermina, Natalia, and Elliot',
    Color: '' },
  { Day: '',
    Time: '7:00',
    'Event Name': 'Creating An Army of Moths - Sky, Children of Light',
    'Staff Name': 'Cath ',
    Color: '' },
  { Day: '',
    Time: '7:30',
    'Event Name': 'Tripping Gentlemen and Stumbling Fellows',
    'Staff Name': 'Ben D',
    Color: '' },
  { Day: '',
    Time: '7:30',
    'Event Name': 'Gartic Phone',
    'Staff Name': 'Zach T',
    Color: '' },
  { Day: '',
    Time: '8:00',
    'Event Name': 'Shell Shockers',
    'Staff Name': 'Ben F',
    Color: '' },
  { Day: '',
    Time: '8:00',
    'Event Name':
     'Fighting Radiant Oblobbles but Every Time we Die we do 5 Push-Ups',
    'Staff Name': 'Andrew, Matt S, and Aaron',
    Color: '' },
  
  { Day: 'Monday',
    Time: '6:30',
    'Event Name': 'Two Rooms and a Boom',
    'Staff Name': 'Geoffery ',
    Color: '' },
 ];

 const events = [ { Day: 'Sunday',
 Time: '5:00',
 'Event Name': 'Among Us',
 'Staff Name': 'Christian',
 Color: '5B7286' },
{ Day: '',
 Time: '5:15',
 'Event Name': 'Gartic Phone',
 'Staff Name': 'Destiny C, Michael K',
 Color: '' },
{ Day: '',
 Time: '6:30',
 'Event Name': 'Smash Bros.',
 'Staff Name': 'Matthew Rabinowitz',
 Color: '' },
{ Day: '',
 Time: '6:30',
 'Event Name': 'GeoGuesser',
 'Staff Name': 'Zach T',
 Color: '' },
{ Day: '',
 Time: '7:00',
 'Event Name': 'Minecraft Party Games',
 'Staff Name': 'Christian',
 Color: '' },
{ Day: '',
 Time: '7:00',
 'Event Name': 'Making Paper Airplanes',
 'Staff Name': 'Matt Samuels',
 Color: '' },
{ Day: '',
 Time: '7:30',
 'Event Name': 'Code Names',
 'Staff Name': 'Elliot, Zach S, Zermina',
 Color: '' },
{ Day: '',
 Time: '7:30',
 'Event Name': 'Shell Shockers',
 'Staff Name': 'Ben F',
 Color: '' },
{ Day: '',
 Time: '8:00',
 'Event Name': 'Mario Kart',
 'Staff Name': 'Siobhan, Sam R',
 Color: '' },

{ Day: 'Monday',
 Time: '6:30',
 'Event Name': 'Pokemon Showdown',
 'Staff Name': 'Matthew Rabinowitz',
 Color: '' },
{ Day: '',
 Time: '6:30',
 'Event Name': 'Gartic Phone',
 'Staff Name': 'Zach T',
 Color: '' },
{ Day: '',
 Time: '7:00',
 'Event Name': 'Disney Princess Enchanted Journey',
 'Staff Name': 'Cath G, Sam R, Gabe S',
 Color: '' },
{ Day: '',
 Time: '7:00',
 'Event Name': 'Elmo Hour',
 'Staff Name': 'Pasquale',
 Color: '' },
{ Day: '',
 Time: '7:30',
 'Event Name': 'Atomic Chess',
 'Staff Name': 'Timo, Keven',
 Color: '' },
{ Day: '',
 Time: '7:30',
 'Event Name': 'Dreamworks Princess Enchanted Adventure',
 'Staff Name': 'Michael K, Aaron L',
 Color: '' },
{ Day: '',
 Time: '8:00',
 'Event Name': 'Minecraft Hypixle Party Games',
 'Staff Name': 'Zach T',
 Color: '' },
{ Day: '',
 Time: '8:00',
 'Event Name': 'Smash Bros. CHAOS',
 'Staff Name': 'Matthew Rabinowitz',
 Color: '' },

{ Day: 'Tuesday',
 Time: '6:30',
 'Event Name': 'Playing My Very EPIC Unity Games',
 'Staff Name': 'Mac',
 Color: '' },
{ Day: '',
 Time: '6:30',
 'Event Name': 'GeoGuesser',
 'Staff Name': 'John R, Ian N',
 Color: '' },
{ Day: '',
 Time: '7:00',
 'Event Name': 'Speedrunning Towers of Hanoi',
 'Staff Name': 'Matt Samuels',
 Color: '' },
{ Day: '',
 Time: '7:00',
 'Event Name': 'Destiny\’s Chill Hour',
 'Staff Name': 'Destiny C',
 Color: '' },
{ Day: '',
 Time: '7:00',
 'Event Name': 'Tripping Gentlemen and Stumbling Fellows',
 'Staff Name': 'Ben D, Keven',
 Color: '' },
{ Day: '',
 Time: '7:30',
 'Event Name': 'Just Dance',
 'Staff Name': 'Sam R',
 Color: '' },
{ Day: '',
 Time: '7:30',
 'Event Name': 'I Love You Colonel Sanders - Dating Simulator',
 'Staff Name': 'Michael K',
 Color: '' },
{ Day: '',
 Time: '8:00',
 'Event Name':
  'Attempting to Radiant Obnoxious Hollow Knight Bosses While Listening to the Macarena Instrumental on Loop Until We Lose Our Minds',
 'Staff Name': 'Aaron L',
 Color: '' },
{ Day: '',
 Time: '8:00',
 'Event Name': 'TF Tuesday',
 'Staff Name': 'Julian G',
 Color: '' },

{ Day: 'Wednesday',
 Time: '6:30',
 'Event Name': 'Cooking Momma Cook Off - Campers v. Staff',
 'Staff Name': 'Sam R, Siobhan M',
 Color: '' },
{ Day: '',
 Time: '6:30',
 'Event Name': 'Fall Guys',
 'Staff Name': 'Elliot, Natalia',
 Color: '' },
{ Day: '',
 Time: '7:00',
 'Event Name': 'Pokemon Soul Link',
 'Staff Name': 'Ben D, Gabe S',
 Color: '' },
{ Day: '',
 Time: '7:00',
 'Event Name': 'Real Facts From Keven (REAL)',
 'Staff Name': 'Keven',
 Color: '' },
{ Day: '',
 Time: '7:30',
 'Event Name': 'Recreating Staff in the Sims 4',
 'Staff Name': 'Cath G',
 Color: '' },
{ Day: '',
 Time: '7:30',
 'Event Name': 'Wheel of Fortune',
 'Staff Name': 'Zach T',
 Color: '' },
{ Day: '',
 Time: '8:00',
 'Event Name': 'Garfield Kart',
 'Staff Name': 'Pasquale',
 Color: '' },
{ Day: '',
 Time: '8:00',
 'Event Name': 'Sleeping Speedrun',
 'Staff Name': 'Aaron',
 Color: '' },

{ Day: 'Thursday',
 Time: '6:30',
 'Event Name':
  'Pantheon of Hallownest but I Can\'t See Well and Possibly With My Hands Tied Behind My Back',
 'Staff Name': 'Aaron L',
 Color: '' },
{ Day: '',
 Time: '6:30',
 'Event Name': 'Roblox Arsenal',
 'Staff Name': 'Julian, Christian',
 Color: '' },
{ Day: '',
 Time: '6:30',
 'Event Name': 'Zach Explains Trains',
 'Staff Name': 'Zach T',
 Color: '' },
{ Day: '',
 Time: '7:00',
 'Event Name': 'Jackbox',
 'Staff Name': 'Michael',
 Color: '' },
{ Day: '',
 Time: '7:00',
 'Event Name': 'Wiki Trail',
 'Staff Name': 'Timo',
 Color: '' },
{ Day: '',
 Time: '7:30',
 'Event Name': 'Rocket League',
 'Staff Name': 'Zach S, Zermina',
 Color: '' },

{ Day: 'Friday',
 Time: '12:30',
 'Event Name': 'Shell Shockers',
 'Staff Name': 'Ben F',
 Color: '' },
{ Day: '',
 Time: '12:30',
 'Event Name': 'Card Games',
 'Staff Name': 'Timo',
 Color: '' },
{ Day: '',
 Time: '1:00',
 'Event Name': 'Connect 4-Square',
 'Staff Name': 'Aaron L, Matt Samuels',
 Color: '' },
{ Day: '',
 Time: '1:00',
 'Event Name': 'Gartic Phone',
 'Staff Name': 'Sam R, Michael',
 Color: '' } ];

//let temp = document.querySelector(".container").getChildren();
let tableRow_template = document.querySelector(".template_row").childNodes[1];
let holder;



let currentDay = 'Sunday';
let currentTable;
 for(let event of events){
 	//Check or update the current Table
 	if(  event.Day !== currentDay && event.Day !== '' )
 		currentDay = event.Day;

 	console.log("Current Day: " + currentDay);

 	//go to the correct table(Sunday-Friday row)
 	currentTable = document.querySelector( "." + currentDay + "-table") ;


 	holder = tableRow_template.cloneNode(true); //Create a new empty row(not yet added)
 	console.log()
 	//Set the correct tvalues of that row
 	holder.querySelector(".event-time").innerText = event.Time + "PM";
 	holder.querySelector(".event-title").innerText = event['Event Name'];
 	holder.querySelector(".event-staff").innerText = event['Staff Name']; 

 	//Append the row the current table
 	currentTable.appendChild(holder); 


 

 }
 // document.querySelector(".container").appendChild(clonedRow);


 //Hide all templates
 document.querySelector(".hide-me").style.display = "none";